# Generated by Django 4.1.4 on 2023-07-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0004_feedbackdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
