# Generated by Django 4.1.4 on 2023-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0007_registrationdata_delete_registerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdata',
            name='Password',
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='password',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
